Replace this repo with a pointer to docs.github.com
github/copilot-docs pull request #53
Opened 2022-07-11 11:36 UTC by hsenag

2022-07-11 11:43 UTC, bmuskalla requested changes

2022-07-11 11:43 UTC, bmuskalla commented on README.md
^^ this should not say tech preview anymore

2022-07-11 11:43 UTC, bmuskalla commented on README.md
>  <img width="128" alt="GitHub Copilot Logo" src="https://user-images.githubusercontent.com/28068/123712981-02676c80-d839-11eb-919a-96ee0c895e15.png">
still the old logo

2022-07-11 11:43 UTC, bmuskalla commented on README.md
> +This repository was used for GitHub Copilot documentation during the technical preview, which has
Should we try to be more positive and forward looking (drop `ended` and use something like the blog post itself `GitHub Copilot is generally available to all developers`)

2022-07-11 12:03 UTC, hsenag commented on README.md
>  <img width="128" alt="GitHub Copilot Logo" src="https://user-images.githubusercontent.com/28068/123712981-02676c80-d839-11eb-919a-96ee0c895e15.png">
Again thought it simpler jsut to reflect that this is the old world.

2022-07-11 12:13 UTC, bmuskalla approved these changes
I'm generally ok with this. I still think we should use the newer logo for all public-facing entities.

2022-07-11 12:38 UTC, hsenag commented on README.md
>  <img width="128" alt="GitHub Copilot Logo" src="https://user-images.githubusercontent.com/28068/123712981-02676c80-d839-11eb-919a-96ee0c895e15.png">
Dropped the logo too

2022-07-11 13:58 UTC, jules-p approved these changes
Looks good to me! 🚀

2022-07-11 15:35 UTC, merged

2023-06-29 10:32 UTC, Hayderhammami reviewed
Good

2023-07-25 21:09 UTC, Someshsw1109 commented
That's awesome

2023-07-25 21:10 UTC, allan1366 commented
来信收到，谢谢！张韶华

2023-08-28 22:43 UTC, Hosamph approved these changes

2023-08-28 22:43 UTC, allan1366 commented
来信收到，谢谢！张韶华